name: Test Full Build
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'LICENSE'

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Test Full Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        target: [win64,win32,linux64,linuxarm64]
        variant: [nonfree,gpl,lgpl,nonfree 5.0,gpl 5.0,lgpl 5.0,nonfree-shared,gpl-shared,lgpl-shared,nonfree-shared 5.0,gpl-shared 5.0,lgpl-shared 5.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install buildx
        uses: docker/setup-buildx-action@v2
        with:
          config: .github/buildkit.toml
          driver: docker
      - name: Build Image
        run: ./makeimage.sh ${{ matrix.target }} ${{ matrix.variant }}
        env:
          QUICKBUILD: ${{ matrix.quickbuild }}
      - name: Build ffmpeg
        run: ./build.sh ${{ matrix.target }} ${{ matrix.variant }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg
          path: artifacts/*
          retention-days: 10
